### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra/aig-shoov#1]
https://www.aig.co.il/

**Comment by DavidKohav** [comment]
![anonymous](https://cloud.githubusercontent.com/assets/5812423/12551009/10dd452a-c370-11e5-8136-f635be56b4e9.jpg)

**Comment by DavidKohav** [comment]
![anonymous1](https://cloud.githubusercontent.com/assets/5812423/12551585/38fcf72c-c374-11e5-8a59-4951e87718ec.jpg)

**Comment by DavidKohav** [comment]
![anonymous1](https://cloud.githubusercontent.com/assets/5812423/12551798/c6cf4edc-c375-11e5-807c-3bc314003e99.jpg)

**Comment by DavidKohav** [comment]
![anonymous1](https://cloud.githubusercontent.com/assets/5812423/12551853/2b6c6014-c376-11e5-9ef1-095952077476.jpg)

**Comment by DavidKohav** [comment]
![anonymous2](https://cloud.githubusercontent.com/assets/5812423/12551980/4d9e8ca6-c377-11e5-8d03-1afe632972e0.jpg)

**Comment by mldk-tech** [comment]
![anonymous2](https://cloud.githubusercontent.com/assets/5812423/12552103/3fa13c56-c378-11e5-9c5b-1466ec6542da.jpg)

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/22026

**Comment by mldk-tech** [comment]
http://gfycat.com/SomberSomeConch
